###

POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "Bob",
    "message": "Hiii this is my second post."
}


###

GET http://localhost:3000/post


###

GET http://localhost:3000/post/696123d9d42f01021a805756