###

DELETE http://localhost:3000/comment/69727103af2af050bd7fb65b
###

PUT http://localhost:3000/comment/69727103af2af050bd7fb65b
Content-Type: application/json

{
    "message": "Updated comment message!!!"
}
###

POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "Bob",
    "message": "Hiii this is my post."
}

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "sender": "Alice",
    "message": "This is a comment!!!!",
    "postId": "696fff7ee600df766246eb8d"
}

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/696fff7ee600df766246eb8d

###

GET http://localhost:3000/post?sender=Bob

###

PUT http://localhost:3000/post/696fff7ee600df766246eb8d
Content-Type: application/json

{
    "message": "Updated message content."
}